server:
  port: 1234
  servlet:
    context-path: /lms
spring:
  datasource:
    url: jdbc:postgresql://ec2-52-203-118-49.compute-1.amazonaws.com:5432/d86nrgfju2v0qr #jdbc:postgresql://localhost:5432/postgres #database name:  #
    username: pvnofkrwmhyrop #postgres # pvnofkrwmhyrop   #changed as per Local DB
    password: cadd6e7c1054583e2bfa9a1075740e4f88f92ac1fddc5db85505a48dd521f7f6 #admin #cadd6e7c1054583e2bfa9a1075740e4f88f92ac1fddc5db85505a48dd521f7f6 #mypostgres   #changed as per Local DB

  jackson.deserialization.fail-on-unknown-properties: true
  jackson.serialization.fail-on-empty-beans: false  # LMSPhase2 changes
  mvc.hiddenmethod.filter.enabled: true
  main.allow-bean-definition-overriding: true
  #hibernate ddl Auto for CURDOperations
  
   jpa.hibernate.ddl-auto: none
  jpa.defer-datasource-initialization: true
  sql.init.mode: always
 # jpa.open-in-view : false
logging:
  file:
    name: lmsservice.log
    path: ./
layout:
  pageInfo:
    program:
      idField: "programId"
      title: "Programs"
      searchField: "programName"
      fieldNames:
        programId: "Program Id"
        programName: "Program Name"
        programDescription: "Program Description"
        programStatus: "Program Status"
    programbatch:   
      idField: "batchId"
      title: "Batches"
      searchField: "batchName"
      fieldNames:
        batchId: "Batch Id"
        batchName: "Batch Name"
        batchDescription: "Batch Description"
        batchStatus: "Batch Status"
        batchProgramId: "Program Id"
        batchNoOfClasses: "No.of.classes"
    class:
      idField: "csId"
      title: "Classes"
      searchField: "classTopic"
      fieldNames:
        csId: "Class Id"
        batchId: "Batch Id"
        classNo: "Class No"
        classDate: "Class Date"
        classTopic: "Class Topic"
        classStaffId: "Staff Id"
        classDescription: "Description"
        classComments: "Comments"
        classNotes: "Notes"
        classRecordingPath: "Recording"
    attendance:
      idField: "attId"
      title: "Attendance"
      searchField: "classId"
      fieldNames:
        attId: "Attendance Id"
        classId: "Class Id"
        studentId: "Student Id"
        attendance: "Attendance"
